version: '3.7'
services:
  kratos-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kratos"]
      interval: 10s
      timeout: 5s
      retries: 5

  keto-db:
    image: postgres:13
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=keto
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=keto
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keto"]
      interval: 10s
      timeout: 5s
      retries: 5

  kratos-migrate:
    image: oryd/kratos:latest
    environment:
      - DSN=postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos/:/etc/config/kratos/
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    depends_on:
      kratos-db:
        condition: service_healthy

  keto-migrate:
    image: oryd/keto:latest
    environment:
      - DSN=postgres://keto:secret@keto-db:5432/keto?sslmode=disable
    volumes:
      - ./keto/:/home/ory/
    command: migrate up -c /home/ory/keto.yml -y
    depends_on:
      keto-db:
        condition: service_healthy

  kratos:
    image: oryd/kratos:latest
    depends_on:
      kratos-db:
        condition: service_healthy
      kratos-migrate:
        condition: service_completed_successfully
    environment:
      - DSN=postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=debug
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    volumes:
      - ./kratos/:/etc/config/kratos/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  keto:
    image: oryd/keto:latest
    depends_on:
      keto-db:
        condition: service_healthy
      keto-migrate:
        condition: service_completed_successfully
    environment:
      - DSN=postgres://keto:secret@keto-db:5432/keto?sslmode=disable
    ports:
      - "4466:4466" # read
      - "4467:4467" # write
    volumes:
      - ./keto/:/home/ory/
    command: serve -c /home/ory/keto.yml

  oathkeeper:
    image: oryd/oathkeeper:latest
    depends_on:
      - kratos
      - keto
    ports:
      - "4455:4455" # proxy
      - "4456:4456" # api
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper
    command: serve -c /etc/config/oathkeeper/oathkeeper.yml

  # นี่คือ Service ตัวอย่างที่เราจะป้องกันการเข้าถึง
  hello_service:
    image: ory/hello-world:latest
    ports:
      - "8080:80"

networks:
  default:
    name: ory-network