apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-identity-schema
  namespace: default
data:
  identity.schema.json: |
    {
      "$id": "https://auth.dossware.com/schemas/default",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email"
            },
            "role": {
              "type": "string",
              "enum": ["user", "admin", "superadmin"],
              "default": "user"
            }
          },
          "required": ["email", "role"]
        }
      }
    }
