dsn: postgres://kratos:kratos@kratos-db:5432/kratos?sslmode=disable

serve:
  public:
    base_url: http://localhost:4434/
    cors:
      enabled: true
  admin:
    base_url: http://localhost:4433/

identity:
  default_schema_url: file:///etc/config/kratos/identity.schema.json
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://localhost:3000/

  flows:
    login:
      ui_url: http://localhost:3000/login
    registration:
      ui_url: http://localhost:3000/register
    settings:
      ui_url: http://localhost:3000/settings
    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery
    verification:
      enabled: true
      ui_url: http://localhost:3000/verify

  methods:
    password:
      enabled: true
    link:
      enabled: true
    code:
      enabled: false

log:
  level: debug
  format: text
  leak_sensitive_values: true
